### ISSUE TITLE
Change repo structure.

### ISSUE THREAD

**Issue by akshatvg** [CodeChefVIT/LeoClub-Website#4]
Put all the HTML files in the root of the repo.
The root should also have a folder called assets which has folders called css, js, img and fonts where you can add the respective files.
Modify the HTML code to incorporate the src and href changes for the location.

**Comment by DiptoChakrabarty** [comment]
Why hasn't this simple issue been sorted out yet  the repository looks messy  change its structure  fast

**Comment by akshatvg** [comment]
@Aarushi21 @yasharthratan
